### ISSUE TITLE
如何部署

### ISSUE THREAD

**Issue by schooljenry** [lidong1665/dubbo2.5-spring4-mybastis3.2-springmvc4-mongodb-redis#1]
可以提供一下sql，以及怎样部署吗？

**Comment by lidong1665** [comment]
很简单 就一张表

CREATE TABLE `user` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(20) NOT NULL,
  `password` varchar(20) NOT NULL,
  `age` int(10) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=42 DEFAULT CHARSET=utf8

**Comment by schooljenry** [comment]
好像还是少了一些jar，少了fastdfs的jar包。
